### ISSUE TITLE
highlight+copy barcode straight from OFF page to OP search box results in Product not found - transit via textfile works

### ISSUE THREAD

**Issue by serpico** [openfoodfacts/open-prices-frontend#574] opened 2024-05-08 10:21 UTC
Epic: #

### Description
1.  start at https://world.openfoodfacts.org/product/7622210796301/monaco-biscuits-crackers-a-l-emmental-belin
2.  highlight EAN after _Barcode:_  ( located above _quantity: 100g_ ) via double-click
3. copy EAN via right-click and contextual menu
4. paste EAN
5. Product not found in Open Food Facts... Don't hesitate to add it :)

repeat steps 1 to 3  but paste into a text editor ( gedit in my case ), highlight and copy from there, product is found.

Same thing happen when you want to copy EAN from OFF page to add a new product

Looks like there's a space added in front of the EAN

**Comment by raphodn** [comment] 2024-05-08 10:54
Where are you pasting the EAN ?

**Comment by serpico** [comment] 2024-05-08 11:31
In the OP search box see attachment

![searchbox](https://github.com/openfoodfacts/open-prices-frontend/assets/1227077/d33e4989-5a5d-4c37-9a48-c44cbb30d8a0)

**Comment by raphodn** [comment] 2024-05-08 13:35
ok ! I'll be on holidays for the next few days.
btw are you on the OFF Slack ? We have a #prices channel ;)

**Comment by raphodn** [comment] 2024-05-22 13:08
On my laptop I can't seem to reproduce :thinking: 
Are you on mobile ?

**Comment by raphodn** [comment] 2024-05-22 13:09
On solution would be to strip spaces when searching (remove any space at the start and at the end of the text)

**Comment by serpico** [comment] 2024-05-22 16:01
> On my laptop I can't seem to reproduce 🤔 Are you on mobile ?

I first noticed the problem when copying from a tab OFF's website on my laptop to the searchbox on OP's [searchbox](https://github.com/openfoodfacts/open-prices-frontend/issues/574#issuecomment-2100368446) on the webapp on mobile ( using KDE connect's clipboard sharing feature). After this message I tried while staying on the laptop, copy from one tab with OFF's website to the next tab containing OP's webapp searchbox but the behavior was the same.

**Comment by serpico** [comment] 2024-05-22 16:06
> One solution would be to strip spaces when searching (remove any space at the start and at the end of the text)

If it's a quick fix to go that way ( a few lines of code ) I'd appreciate if we could give this a try and if it doesn't work we'll move on, either close the issue or keep it for reference but without plan to dig deeper until someone else report it.

**Comment by raphodn** [comment] 2024-05-22 21:40
Could you try on a phone ? Or on another laptop ? Or send a video ?

I can't reproduce, so it could come from your OS.. ?

**Comment by serpico** [comment] 2024-05-23 05:05
here's a video entirely on mobile

https://transfert.free.fr/8gpgVe1

I'll try all on a windows laptop soon and report

PS: I tried to upload the file here on github but it was > 10MB, used ffmpeg to get it down to 2.5 then there was a message about mime type...

**Comment by raphodn** [comment] 2024-05-23 14:55
Thanks a lot for the video !

So i did some tests, and dug inside the code
- the input field si already set to "numeric", so if you paste something with whitespaces it already removes them automatically :thinking: 
- I did some tweaks in this PR #582 that I just merged

Could you try to test again in the staging environment ? https://prices.openfoodfacts.net/app/

**Comment by serpico** [comment] 2024-05-23 15:49
Thank you to keep trying!!! ( I realize it's kinda trivial and related to my workflow :smile: )

All the following was done on desktop.

It seems the problem comes from the "copying from OFF" part as : 
when I select and copy the EAN and see this ( a screenshot I took from OFF )
![testnospace](https://github.com/openfoodfacts/open-prices-frontend/assets/1227077/55b67943-c0be-4f1f-bf33-05d946dcfa35)
I'm thinking, ok only the selected/highlighted part is being copied (so there will be no space).
However when I paste on a text editor the "problematic" space before the EAN is already there (as it would be if I pasted on the OP searchbox).

Is it the same behavior on your machine?

PS: I noticed a change, my screenshoter allows me to draw a zone to screenshot.

- If the EAN string begins with the space it will disappear as soon as I activate the "draw" mode (but the EAN is still screenshot somehow in the resulting file).

- If the EAN string is "conform" ( no space, copied "cleanly" from a text editor for example ) it doesn't disappear ( no change whether the draw mode is activated or not ).

Before it was the same in both case, space or no space, there was no "disappearance" whether the draw mode was activated or not.

**Comment by raphodn** [comment] 2024-05-31 09:44
With Brave + Ubuntu I can't reproduce the "copying the barcode from OFF comes with a space". 

BUT with Firefox + Ubuntu I indeed have this problem :eyes: 
- https://support.mozilla.org/en-US/questions/950377
- https://support.mozilla.org/en-US/questions/1011667

I guess this is a Firefox issue...

**Closed by raphodn** 2024-05-31 09:44 UTC
